#!/bin/bash

echo Creating python3 virtual environment named env-s...
python3 -m venv env-s
echo sourcing virtual environment...
source env-s/bin/activate
echo installing stock-comparer app requirements...
pip install -r app/requirements.txt
